version: 2.1
orbs:
  docker: circleci/docker@2.2.0
executors:
  docker-publisher:
    docker:
      - image: cimg/base:2023.02
jobs:
  build:
    docker:
      - image: cimg/go:1.20
        auth:
          username: twosharks
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt update -y && sudo apt install -y libpcap-dev
      - run:
          name: Build
          command: make build

  test:
    docker:
      - image: cimg/go:1.20
        auth:
          username: twosharks
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt update -y && sudo apt install -y libpcap-dev
      - run:
          name: Run Tests
          command: make test

  lint:
    docker:
      - image: golangci/golangci-lint:v1.51
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update -y && apt install -y libpcap-dev
      - run:
          name: gofumpt install
          command: go install mvdan.cc/gofumpt@latest
      - run:
          name: Lint
          command: make lint

workflows:
  version: 2
  balanceProxy:
    jobs:
      - lint
      - test
      - build
      - docker/publish:
          image: twosharks/balanceproxy
          tag: ${CIRCLE_SHA1:0:7},$CIRCLE_BRANCH

