apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    {{- include "ethBalanceProxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ethBalanceProxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.proxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ethBalanceProxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: proxy
          command: [ "ethBalanceProxy" ]
          args: [ "server", "--upstreams", {{ .Values.proxy.endpoints | quote}} ]
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
            - name: proxy
              containerPort: {{ .Values.proxy.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: proxy
          readinessProbe:
            httpGet:
              path: /ready
              port: proxy
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
