apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    {{- include "ethBalanceProxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.proxy.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ethBalanceProxy.selectorLabels" . | nindent 4 }}
