apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxy
  labels:
    {{- include "ethBalanceProxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ethBalanceProxy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: proxy
      path: /metrics
      interval: 30s